language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
env:
    global:
        - secure: IGtzfkqAJtqknot0EWwFW8WGBI9vjbrxe2w6Dwi8IFfm+MLA0zvHVZKvuqtY0muBMFiMbcC/7yA2AZJQgMVrx5ksExOvhqnbc/YVtnTBJSyT1Aoas5XpSXc7VzLg5jxMDAEJPPKDzuiCVx+aaTIACmgi9Ww/KVGKqmaAhebQW+k=
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
